name: api

services:
  php:
    build:
      context: ../infra/docker/php
      dockerfile: Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../src:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  nginx:
    build:
      context: ../infra/docker/nginx
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ../src:/var/www/html
      - ../infra/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - php-fpm-socket:/var/run/php-fpm

  db:
    build:
      context: ../infra/docker/mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ../infra/docker/mysql/storage/:/var/lib/mysql
      - ../infra/docker/mysql/initdb/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  php-fpm-socket:
  db-store:
